samples: "samples.tsv"
units: "units.tsv"

qual_type: "sanger"

host_index:
  fasta: "data/host/hg38_head1000.fa"
  prefix: "data/host/hg38_head1000.fa"

params:
  trim:
    sickle_pe: ""
    sickle_se: ""
  rmhost:
    bwa_mem_threads: 8
    samtools_threads: 8
  assembly:
    megahit:
      threads: 8
      min_contig: 500
  alignment:
    bwa_mem_threads: 8
    samtools_threads: 8
  binning:
    metabat2:
      min_contig: 2500
      seed: 2018
  checkm:
    env: "bioenv2"
    threads: 8
    completeness: 90
    contamination: 10
  drep: ""

results:
  trim: "data/01.trimmed"
  rmhost: "data/02.rmhost"
  assembly: "data/03.assembly"
  alignment: "data/04.alignment"
  binning: "data/05.binning"
  checkm: "data/06.checkm"
  drep: "data/07.drep"
  annotation: "data/08.annotation"

logs:
  trim: "data/logs/01.trimmed"
  rmhost: "data/logs/02.rmhost"
  assembly: "data/logs/03.assembly"
  alignment: "data/logs/04.alignment"
  binning:
    metabat2: "data/logs/05.binning/metabat2"
  checkm: "data/logs/06.checkm"
  drep: "data/logs/07.drep"
  annotation: "data/logs/08.annotation"
