params:
  reads_layout: "pe"
  fq_encoding: "sanger"
  samples: "samples.tsv"
  simulate:
    do: True
    genomes: "genomes.tsv"
    threads: 8
  fastqc:
    do: True
    threads: 8
  trimming:
    oas1:
      do: False
      quality_system: 33
      min_length: 30
      seed_oa: 0.9
      fragment_oa: 0.8
    sickle:
      do: False
      quality_type: "sanger"
      sickle_pe: ""
      length_cutoff: 51
      quality_cutoff: 20
    fastp:
      do: True
      threads: 4
      disable_adapter_trimming: True
      use_slide_window: True
      compression: 6
      cut_front_window_size: 4
      cut_front_mean_quality: 20
      cut_tail_window_size: 4
      cut_tail_mean_quality: 20
      cut_right_window_size: 4
      cut_right_mean_quality: 20
      length_required: 51
      n_base_limit: 5
  rmhost:
    host_fasta: /home/alienzj/databases/genomepy/hg38/hg38.fa
    threads: 8
    save_bam: False
    compression: 6
    bwa:
      do: False
      index_prefix: /home/alienzj/databases/genomepy/hg38/index/bwa/hg38.fa
      minimum_seed_length: 23
    bowtie2:
      do: True
      index_prefix: /home/alienzj/databases/genomepy/hg38/index/bowtie2/hg38
  qc_report:
    seqkit:
      do: True
      threads: 4
  assembler: ["megahit", "idba_ud", "metaspades", "spades"]
  assembly:
    report:
      do: true
      threads: 8
      len_ranges: [0, 1000, 1500, 2000, 2500, 3000]
    megahit:
      do: False
      threads: 8
      min_contig: 500
    idba_ud:
      do: False
      mink: 27
      maxk: 127
      step: 10
      min_contig: 500
      threads: 8
    metaspades:
      do: True
      only_assembler: False
      only_save_scaftigs: True
      memory: 20
      threads: 8
      kmers: ['21', '29', '39', '59', '79', '99']
    spades:
      do: False
      only_assembler: False
      only_save_scaftigs: False
      memory: 20
      threads: 8
      kmers: ['21', '29', '39', '59', '79', '99']
  coassembly:
    megahit:
      do: False
      threads: 8
      min_contig: 500
    demultiplex_kraken2:
      do: False
      rank: "genus"
      taxadb: /path/to/ncbi_taxonomy.database/
      change_seq_id: True
  metaquast:
    do: False
    threads: 8
    min_contig: 500
    env: "bioenv2"
  prediction:
    prodigal:
      do: False
      format: "gff"
      mode: "meta"
  alignment:
    do: True
    threads: 8
    cal_base_depth: False
    report: True
  binning:
    binner: "metabat2"
    metabat2:
      do: True
      min_contig: 1500
      seed: 2020
    maxbin2:
      do: False
      threads: 8
  cobinning:
    do: False
    rename: False
    renamed_id: "samples_id_renamed.tsv"
    samples_id: "samples_id.txt"
    threads: 8
    scaftigs_length: 1000
    vsearch:
      identity: 0.75
  checkm:
    do: True
    report: True
    threads: 8
    completeness: 90
    contamination: 10
    standard: "MIMAG" # SGB
  dereplication:
    drep:
      do: True
      threads: 8
      filtering_genome_min_length: 50000
      filtering_completeness: 75
      filtering_contamination: 25
      genome_comparison_algorithm: "ANImf"
      clustering_primary_ANI: 0.9
      clustering_secondary_ANI: 0.99
  classification:
    kraken2:
      do: True
      database: /path/to/kraken2/database
      threads: 8
    gtdbtk:
      do: True
      database: /path/to/gtdbtk/database
      extension: "fa"
      reduce_memory: True
      threads: 8
  annotation:
    prokka:
      do: True
      kingdom: Bacteria
      metagenome: False
      threads: 8
  profiling:
    threads: 8
    index_metadata: /path/to/index_metadata
    taxonomy: /path/to/taxonomy
    metaphlan2:
      do: True
      threads: 8
      bowtie2db: "/path/to/metaphlan_databases"
      index: "latest"
      taxonomic_level: "a"
      analysis_type: "rel_ab_w_read_stats"
      no_unknown_estimation: False
      input_type: "fastq"
      min_cu_len: 2000
      read_min_len: 70
    jgi:
      do: True
      fragment: 1200
      memory_limit: 2G
      index_prefix: /path/to/bowtie2_index_prefix
    humann2:
      do: True
      threads: 8
      remove-temp-output: True
      normalize_method: "relab"
      regroup_method: "sum"
      map_database: ["uniref90_go", "uniref90_ko", "uniref90_eggnog", "uniref90_pfam", "uniref90_level4ec", "uniref90_infogo1000", "uniref90_rxn"]
  burst:
    do: False
    references: "/path/to/references.edx"
    accelerator: "/path/to/accelerator.acx"
    identity: 0.97
    mode: "ALLPATHS"
    threads: 8

output:
  sra2fq: "results/00.sra2fq"
  simulate: "results/00.simulate"
  raw: "results/00.raw"
  trimming: "results/01.trimming"
  rmhost: "results/02.rmhost"
  assembly: "results/03.assembly"
  coassembly:
    megahit: "results/03.coassembly/megahit"
    demultiplex_kraken2: "results/03.coassembly/demultiplex_kraken2"
  upload: "results/03.upload"
  metaquast: "results/03.metaquast"
  prediction: "results/04.prediction"
  alignment: "results/04.alignment"
  binning:
    depth: "results/05.binning/coverage"
    bins: "results/05.binning/bins"
  cobinning:
    scaftigs: "results/05.cobinning/scaftigs"
    cds: "results/05.cobinning/cds"
    depth: "results/05.cobinning/depth"
  checkm:
    base_dir: "results/06.checkm"
    out: "results/06.checkm/checkm_out"
    data: "results/06.checkm/checkm_data"
    coverage: "results/06.checkm/checkm_coverage"
    profile: "results/06.checkm/checkm_profile"
  dereplication: "results/07.dereplication"
  classification: 
    kraken2: "results/08.classification/kraken2"
    gtdbtk:
      base_dir: "results/08.classification/gtdbtk_out"
  annotation:
    prokka: "results/09.annotation/prokka"
    multiqc_prokka: "results/09.annotation/multiqc_prokka"
  profiling:
    metaphlan2:
      base_dir: "results/10.profiling/metaphlan2"
      bowtie2_out: "results/10.profiling/metaphlan2/bowtie2out"
      profile: "results/10.profiling/metaphlan2/profile"
    jgi:
      depth: "results/10.profiling/jgi/depth"
      profile: "results/10.profiling/jgi/profile"
    humann2: "results/10.profiling/humann2"
  burst: "results/12.burst"

upload:
  do: False
  threads: 8
  project_accession: "CNP0000000"

  samples:
    sample_title: ""
    tax_id: "447426"
    organism: "human oral metagenome"
    common_name: ""
    investigation_type: "metagenome"
    collection_date: "2018-11-19"
    env_biom: "saliva"
    env_feature: "saliva"
    env_material: "saliva material"
    geo_loc_name: "China: Shenzhen"
    host: "Homo sapiens"
    lat_lon: "22.35 N 114.27 E"
    strain: "missing"
    estimated_size: "missing"
    isol_growth_condt: "not collected"
    num_replicons: "not collected"
    ref_biomaterial: "not collected"
    ploidy: "missing"
    propagation: "not collected"

  sequencing_run:
    experiment_title: "WGS of human oral metagenome"
    library_name: "LIBRARY_NAME-BARCODE_ID"
    library_strategy: "WGS"
    library_source: "METAGENOMIC"
    library_selection: "RANDOM"
    library_layout: "paired"
    platform: "BGISEQ"
    instrument_model: "BGISEQ-500"
    design_description: "human oral metagenome"
    library_construction_protocol: "RANDOM"
    nominal_size: "350"
    file_type: "fastq"

  assembly:
    assembly_method: "SPAdes"
    assembly_method_version: "v3.13.0"
    assembly_partial: True
    assembly_coverage: "30"
    sequencing_technology: "BGISEQ"
    assembly_min_gap_length: ""
    assembly_mol_type: "genomic DNA"
    reference_genome: ""
