params:
  reads_format: "fastq"
  reads_layout: "pe"
  samples: "samples.tsv"
  begin: "raw"
  simulation:
    do: False
    taxid: ["362948", "321967", "1125630", "702459", "226186", "272563"]
    genomes: ''
    n_genomes: 4
    n_reads: "5M"
    model:  "hiseq"
    threads: 8
  fastqc:
    do: False
    threads: 8
  trimming:
    oas1:
      do: False
      qual_system: 33
      min_length: 30
      seed_oa: 0.9
      fragment_oa: 0.8
    sickle:
      do: False
      qual_type: "sanger"
      sickle_pe: ""
      length_cutoff: 51
      qual_cutoff: 20
    fastp:
      do: True
      threads: 4
      disable_adapter_trimming: True
      use_slide_window: True
      compression: 6
      cut_front_window_size: 4
      cut_front_mean_quality: 20
      cut_tail_window_size: 4
      cut_tail_mean_quality: 20
      cut_right_window_size: 4
      cut_right_mean_quality: 20
      length_required: 51
      n_base_limit: 5
  rmhost:
    do: True
    host_fasta: /path/to/host.fa
    bwa:
      do: False
      index_prefix: /path/to/host.fa
      threads: 8
      minimum_seed_length: 23
      save_bam: False
    bowtie2:
      do: True
      index_prefix: /path/to/host
      threads: 8
      save_bam: False
      additional_params: "--no-unal"
  assembler: ["megahit", "idba_ud", "metaspades", "spades"]
  assembly:
    megahit:
      do: False
      threads: 8
      min_contig: 500
    idba_ud:
      do: False
      mink: 27
      maxk: 127
      step: 10
      min_contig: 500
      threads: 8
    metaspades:
      do: True
      only_assembler: False
      only_save_scaftigs: False
      memory: 20
      threads: 8
      kmers: ['21', '29', '39', '59', '79', '99']
    spades:
      do: False
      only_assembler: False
      only_save_scaftigs: False
      memory: 20
      threads: 8
      kmers: ['21', '29', '39', '59', '79', '99']
  coassembly:
    megahit:
      do: False
      threads: 8
      min_contig: 500
    demultiplex_kraken2:
      do: False
      rank: "genus"
      taxadb: /path/to/ncbi_taxonomy.database/
      change_seq_id: True
  metaquast:
    do: False
    threads: 8
    min_contig: 500
    env: "bioenv2"
  prediction:
    prodigal:
      do: False
      format: "gff"
      mode: "meta"
  alignment:
    threads: 8
  binning:
    metabat2:
      do: True
      min_contig: 1500
      seed: 2020
    maxbin2:
      do: False
      threads: 8
  cobinning:
    do: False
    rename: False
    renamed_id: "samples_id_renamed.tsv"
    samples_id: "samples_id.txt"
    threads: 8
    scaftigs_length: 1000
    vsearch:
      identity: 0.75
  checkm:
    env: "bioenv2"
    threads: 8
    completeness: 90
    contamination: 10
  dereplication: ""
  classification:
    kraken2:
      do: False
      database: /path/to/kraken2/database
      threads: 8
  annotation:
    prokka:
      kingdom: Bacteria
      metagenome: False
      threads: 8
  profiling:
    threads: 8
    index_metadata: /path/to/index_metadata
    taxonomy: /path/to/taxonomy
    metaphlan2:
      do: False
      threads: 8
      bowtie2db: "/path/to/metaphlan_databases"
      index: "latest"
      taxonomic_level: "a"
      analysis_type: "rel_ab_w_read_stats"
      no_unknown_estimation: False
      input_type: "fastq"
      min_cu_len: 2000
      read_min_len: 70
    jgi:
      do: False
      fragment: 1200
      memory_limit: 2G
      index_prefix: /path/to/bowtie2_index_prefix
    humann2:
      do: False
      threads: 8
      remove-temp-output: True
  burst:
    references: "/path/to/references.edx"
    accelerator: "/path/to/accelerator.acx"
    identity: 0.97
    mode: "ALLPATHS"
    threads: 8

results:
  sra2fq: "results/00.sra2fq"
  simulation: "results/00.simulation"
  raw:
    reads: "results/00.raw/reads"
    fastqc: "results/00.raw/fastqc"
    multiqc: "results/00.raw/multiqc"
  trimming: "results/01.trimming"
  rmhost: "results/02.rmhost"
  assembly: "results/03.assembly"
  coassembly:
    megahit: "results/03.coassembly/megahit"
    demultiplex_kraken2: "results/03.coassembly/demultiplex_kraken2"
  metaquast: "results/03.metaquast"
  prediction: "results/04.prediction"
  alignment: "results/04.alignment"
  binning:
    depth: "results/05.binning/coverage"
    bins: "results/05.binning/bins"
  cobinning:
    scaftigs: "results/05.cobinning/scaftigs"
    cds: "results/05.cobinning/cds"
    depth: "results/05.cobinning/depth"
  checkm:
    out: "results/06.checkm/checkm_out"
    data: "results/06.checkm/checkm_data"
    coverage: "results/06.checkm/checkm_coverage"
    profile: "results/06.checkm/checkm_profile"
  dereplication: "results/07.dereplication"
  classification: 
    kraken2: "results/08.classification/kraken2"
  annotation:
    prokka: "results/09.annotation/prokka"
    multiqc_prokka: "results/09.annotation/multiqc_prokka"
  profiling:
    metaphlan2:
      base_dir: "results/10.profiling/metaphlan2"
      bowtie2_out: "results/10.profiling/metaphlan2/bowtie2out"
      profile: "results/10.profiling/metaphlan2/profile"
    jgi:
      depth: "results/10.profiling/jgi/depth"
      profile: "results/10.profiling/jgi/profile"
    humann2: "results/10.profiling/humann2"
  burst: "results/12.burst"

logs:
  simulation: "assay/00.simulation/iss_logs"
  raw:
    fastqc: "assay/00.raw/fastqc_logs"
    multiqc: "assay/00.raw/multiqc_logs"
  trimming: "assay/01.trimming/logs"
  rmhost: "assay/02.rmhost/logs"
  assembly:
    megahit: "assay/03.assembly/megahit_logs"
    idba_ud: "assay/03.assembly/idba_ud_logs"
    metaspades: "assay/03.assembly/metaspades_logs"
    spades: "assay/03.assembly/spades_logs"
  coassembly:
    megahit: "assay/03.coassembly/megahit_logs"
    demultiplex_kraken2: "assay/03.coassembly/demultiplex_krakne2_logs"
  metaquast: "assay/03.metaquast/metaquast_logs"
  prediction: "assay/04.prediction/logs"
  alignment: "assay/04.alignment/logs"
  binning:
    metabat2: "assay/05.binning/metabat2_logs"
    maxbin2: "assay/05.binning/maxbin2_logs"
  cobinning: "assay/05.cobinning/logs"
  checkm: "assay/06.checkm/logs"
  dereplication: "assay/07.dereplication/logs"
  classification:
    kraken2: "assay/08.classification/kraken2_logs"
  annotation:
    prokka: "assay/09.annotation/prokka_logs"
  profiling:
    metaphlan2: "assay/10.profiling/metaphlan2_logs"
    jgi: "assay/10.profiling/jgi_logs"
    humann2: "assay/10.profiling/humann2_logs"
  burst: "assay/12.burst/burst12_logs"
