# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.5
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/.test

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "environment.yml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -b -p $HOME/bioenv
            echo "conda activate" >> ~/.bashrc
            conda activate
            conda update -q conda
            conda config --add channels defaults
            conda config --add channels conda-forge
            conda config --add channels bioconda
            conda create -q -n bioenv snakemake python=3.6
            conda activate bioenv
            conda install -r evrionment.yaml

      - save_cache:
          paths:
            - ~/bioenv
          key: v1-dependencies-{{ checksum "environment.yaml" }}
        
      - run:
          name: run tests
          command: |
            conda activate bioenv
            cd .test
            snakemake
