{% set name = "metapi" %}
{% set version = "0.7.5" %}
{% set sha256 = "99ee65de9bd10738d6e65b4156dc7a218e20675907352e5eff94d82647e85a2b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --ignore-installed
  entry_points:
    - metapi = metapi.corer:main

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - numpy
    - pandas
    - openpyxl
    - biopython >=1.73
    - ruamel.yaml
    - snakemake >=5.10
#    - insilicoseq
#    - fastqc
#    - seqtk
#    - seqkit
#    - multiqc
#    - pigz
#    - fastp
#    - sickle-trim
#    - bwa
#    - bowtie2
#    - samtools
#    - megahit
#    - idba
#    - spades
#    - quast
#    - metabat2
#    - maxbin2
#    - vsearch
#    - prodigal
#    - prokka
#    - checkm-genome
#    - drep
#    - kraken2
#    - gtdbtk

test:
  imports:
    - metapi

  commands:
    - metapi --version
    - metapi init --help
    - metapi denovo_wf --help

about:
  home: https://github.com/ohmeta/metapi
  summary: 'metapi is a pipeline to construct a genome catalogue from metagenomics data'
  license: GPL3
  license_family: GPL

extra:
  identifiers:
    - biotools:metapi
  recipe-maintainers:
    - alienzj
