params:
  simulate:
    taxid: ["362948", "321967", "1125630", "702459", "226186", "272563"]
    model:  "hiseq"
    output_prefix:
      X10: "simulate_10X"
      X50: "simulate_50X"
      X100: "simulate_100X"
    coverage:
      X10: "2M"
      X50: "10M"
      X100: "20M"
    threads: 16
  trim:
    qual_type: "sanger"
    sickle_pe: ""
    sickle_se: ""
    length_cutoff: 45
    qual_cutoff: 20
  rmhost:
    do: False
    bwa_mem_threads: 8
    samtools_threads: 8
  assembly:
    megahit:
      do: True
      threads: 8
      min_contig: 500
    idba_ud:
      do: True
      mink: 27
      maxk: 127
      step: 10
      min_contig: 500
      threads: 8
    metaspades:
      do: True
      memory: 10
      threads: 8
      kmers: []
  alignment:
    bwa_mem_threads: 8
    samtools_threads: 8
  binning:
    metabat2:
      do: True
      min_contig: 2500
      seed: 2018
    maxbin2:
      do: True
      threads: 8
  checkm:
    env: "bioenv2"
    threads: 8
    completeness: 90
    contamination: 10
  drep: ""
  classification: ""
  annotation: ""

results:
  config: "metaconfig.yaml"
  host:
    fasta: "results/host/host.fa"
    prefix: "results/host/host.fa"
  simulate:
    genome: "results/simulate"
  raw:
    samples: "results/00.raw/samples.tsv"
    fastqc: "results/00.raw/fastqc"
  trim: "results/01.trim"
  rmhost: "results/02.rmhost"
  assembly: "results/03.assembly"
  alignment: "results/04.alignment"
  binning:
    depth: "results/05.binning/coverage"
    bins: "results/05.binning/bins"
  checkm: "results/06.checkm"
  dereplication: "results/07.dereplication"
  classification: "results/08.classification"
  annotation: "results/09.annotation"

logs:
  trim: "assay/01.trim/logs"
  rmhost: "assay/02.rmhost/logs"
  assembly:
    megahit: "assay/03.assembly/megahit_logs"
    idba_ud: "assay/03.assembly/idba_ud_logs"
    metaspades: "assay/03.assembly/metaspades_logs"
  alignment: "assay/04.alignment/logs"
  binning:
    metabat2: "assay/05.binning/metabat2_logs"
    maxbin2: "assay/05.binning/maxbin2_logs"
  checkm: "assay/06.checkm/logs"
  drep: "assay/07.drep/logs"
  classification: "assay/08.classification/logs"
  annotation: "assay/09.annotation/logs"
