params:
  trim:
    qual_type: "sanger"
    sickle_pe: ""
    sickle_se: ""
    length_cutoff: 45
    qual_cutoff: 20
  rmhost:
    bwa_mem_threads: 8
    samtools_threads: 8
  assembly:
    megahit:
      threads: 8
      min_contig: 500
  alignment:
    bwa_mem_threads: 8
    samtools_threads: 8
  binning:
    metabat2:
      min_contig: 2500
      seed: 2018
  checkm:
    env: "bioenv2"
    threads: 8
    completeness: 90
    contamination: 10
  drep: ""
  classification: ""
  annotation: ""

results:
  host: "results/host/host.fa"
  raw:  "results/00.raw/fastq.tsv"
  trim: "results/01.trim"
  rmhost: "results/02.rmhost"
  assembly: "results/03.assembly"
  alignment: "results/04.alignment"
  binning: "results/05.binning"
  checkm: "results/06.checkm"
  drep: "results/07.drep"
  classification: "results/08.classification"
  annotation: "results/09.annotation"

logs:
  trim: "assay/01.trim/logs"
  rmhost: "assay/02.rmhost/logs"
  assembly: "assay/03.assembly/logs"
  alignment: "assay/04.alignment/logs"
  binning: "assay/05.binning/logs"
  checkm: "assay/06.checkm/logs"
  drep: "assay/07.drep/logs"
  classification: "assay/08.classification/logs"
  annotation: "assay/09.annotation/logs"