params:
  cluster:
    queue: "st.q"
    project: "st.m"
  simulation:
    taxid: ["362948", "321967", "1125630", "702459", "226186", "272563"]
    genomes: ''
    n_genomes: 6
    n_reads: "5M"
    model:  "hiseq"
    output_prefix: "simulate"
    threads: 8
  trimming:
    sickle:
      do: False
      qual_type: "sanger"
      sickle_pe: ""
      length_cutoff: 51
      qual_cutoff: 20
    fastp:
      do: True
      threads: 8
      disable_adapter_trimming: True
      compression: 6
      cut_mean_quality: 20
      length_required: 51
  rmhost:
    do: False
    bwa_mem_threads: 8
    samtools_threads: 8
  assembly:
    megahit:
      do: True
      threads: 8
      min_contig: 500
    idba_ud:
      do: True
      mink: 27
      maxk: 127
      step: 10
      min_contig: 500
      threads: 8
    metaspades:
      do: True
      memory: 10
      threads: 8
      kmers: []
  alignment:
    bwa_mem_threads: 8
    samtools_threads: 8
  binning:
    metabat2:
      do: True
      min_contig: 2500
      seed: 2018
    maxbin2:
      do: False
      threads: 8
  checkm:
    env: "bioenv2"
    threads: 8
    completeness: 90
    contamination: 10
  dereplication: ""
  classification: ""
  annotation: ""

results:
  host:
    fasta: "results/00.host/host.fa"
    prefix: "results/00.host/host.fa"
  simulation:
    genomes: "results/00.simulation"
  raw:
    samples: "results/00.raw/samples.tsv"
    fastqc: "results/00.raw/fastqc"
  trimming: "results/01.trimming"
  rmhost: "results/02.rmhost"
  assembly: "results/03.assembly"
  alignment: "results/04.alignment"
  binning:
    depth: "results/05.binning/coverage"
    bins: "results/05.binning/bins"
  checkm:
    links: "results/06.checkm/checkm_input"
    out: "results/06.checkm/checkm_out"
    data: "results/06.checkm/checkm_data"
  dereplication: "results/07.dereplication"
  classification: "results/08.classification"
  annotation: "results/09.annotation"

logs:
  simulation:
  trimming: "assay/01.trimming/logs"
  rmhost: "assay/02.rmhost/logs"
  assembly:
    megahit: "assay/03.assembly/megahit_logs"
    idba_ud: "assay/03.assembly/idba_ud_logs"
    metaspades: "assay/03.assembly/metaspades_logs"
  alignment: "assay/04.alignment/logs"
  binning:
    metabat2: "assay/05.binning/metabat2_logs"
    maxbin2: "assay/05.binning/maxbin2_logs"
  checkm: "assay/06.checkm/logs"
  dereplication: "assay/07.dereplication/logs"
  classification: "assay/08.classification/logs"
  annotation: "assay/09.annotation/logs"
